# Generated by Django 3.2.5 on 2021-08-15 08:52

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('title', models.CharField(max_length=100, null=True)),
                ('price', models.FloatField(null=True)),
                ('paid_date', models.DateTimeField(default=datetime.datetime(2021, 8, 15, 10, 52, 38, 368060), null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('split_with', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_split', to='users.profile')),
            ],
        ),
    ]
