# Generated by Django 3.2.5 on 2021-10-18 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='groupuser',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(through='groups.GroupUser', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='expensecomment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupuser'),
        ),
        migrations.AddField(
            model_name='expensecomment',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.expense'),
        ),
        migrations.AddField(
            model_name='expensecomment',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupuser'),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_by', to='groups.groupuser'),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_with',
            field=models.ManyToManyField(related_name='expense_split', to='groups.GroupUser'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.expense'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='group_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupuser'),
        ),
    ]
