# Generated by Django 3.2.5 on 2021-08-15 08:56

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 10, 56, 59, 92891), null=True),
        ),
        migrations.CreateModel(
            name='GroupUser',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True, verbose_name=uuid.uuid4)),
                ('balance', models.FloatField(null=True)),
                ('created_expenses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.expense')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
