# Generated by Django 3.2.5 on 2021-08-15 09:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0002_auto_20210815_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_users',
            field=models.ManyToManyField(through='groups.GroupUser', to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 15, 11, 22, 30, 472530), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.profile'),
        ),
    ]
