# Generated by Django 3.2.5 on 2021-10-18 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_expense_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='last_update',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 22, 50, 45, 449832), null=True),
        ),
    ]
