# Generated by Django 3.2.5 on 2021-08-23 18:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20210815_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='comment',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 20, 41, 43, 899802), null=True),
        ),
    ]
