# Generated by Django 3.2.5 on 2021-10-18 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20211018_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 18, 23, 7, 26, 390896), null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
