# Generated by Django 3.2.5 on 2021-10-12 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_auto_20211010_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('name', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 22, 36, 25, 571398), null=True),
        ),
    ]
