# Generated by Django 3.2.5 on 2021-10-12 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0024_alter_expense_paid_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 22, 38, 23, 601206), null=True),
        ),
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
