# Generated by Django 3.2.5 on 2021-10-12 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_auto_20211012_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationType',
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 12, 22, 40, 53, 597718), null=True),
        ),
    ]
